### ISSUE TITLE
v1: fix build with upstream juju/httprequest

### ISSUE THREAD

**Issue by aviau** [go-macaroon-bakery/macaroon-bakery#185]
I am trying to upload macaroon-bakery to Debian.

However, Debian does not allow vendoring dependencies. macaroon-bakery has to build with the latest version of juju/httprequest.

I am getting the following errors:
```
src/gopkg.in/macaroon-bakery.v1/httpbakery/error.go:31:14: undefined: httprequest.ErrorMapper
src/gopkg.in/macaroon-bakery.v1/httpbakery/visitor.go:112:28: cannot use req (type *http.Request) as type "golang.org/x/net/context".Context in argument to httpReqClient.Do:
	*http.Request does not implement "golang.org/x/net/context".Context (missing Deadline method)

```

**Comment by rogpeppe** [comment]
You will need to have some kind of dependency management system, rather than using the latest version of each dependency. We've now added a go.mod file to declare the dependencies, usable with Go 1.11.
