### ISSUE TITLE
http 407 Proxy Authentication Required used in a non-standard way.

### ISSUE THREAD

**Issue by jrwren** [go-macaroon-bakery/macaroon-bakery#56]
rfc2616 section 10.4.8 says
The proxy MUST return a Proxy-Authenticate header field (section 14.33) containing a challenge applicable to the proxy for the requested resource.

The response generated doesn't have this header, I don't think.

I raise this issue only to start the discussion on if this is a good or bad thing and also so that we have some documentation around this use of 407 Proxy Authentication Required.

**Comment by jrwren** [comment]
https://code.google.com/p/chromium/issues/detail?id=372136

"Oh man, I hate it when I'm right" - http://www.azlyrics.com/lyrics/weirdalyankovic/albuquerque.html

**Comment by rogpeppe** [comment]
We've stopped using a 407 response.
